name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      PUBLIC_API_URL: ${{ secrets.PUBLIC_API_URL }}
      PUBLIC_BASE_URL: ${{ secrets.PUBLIC_BASE_URL }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Use pnpm 🗜️
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
          run_install: false

      - name: Use Node.js 🐢
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0
          cache: 'pnpm'

      - name: Install dependencies ⚙️
        run: pnpm install

      - name: Build 🛠️
        run: pnpm build

      - name: CNAME file 🌐
        run: echo 'tools.erian.dev' > dist/CNAME

      - name: Disable Jekyll ⛔
        run: touch dist/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist